name: pipx Install
description: Install Python CLI packages with pipx
author: brandonlwhite@gmail.com

inputs:
  config-file:
    description: Path to the TOML file that specifies the [tool.pipx-install] section and list of packages to install
    default: pyproject.toml

runs:
  using: node20
  main: dist/index.js
